<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Chile</name>
   <tag></tag>
   <elementGuidId>01cfd44a-8b27-4037-9b2d-2d499dd3a045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/div[2]/form/div/div[2]/div[2]/div[16]/div/div/div/tags-input/div/auto-complete/div/ul/li[9]/ti-autocomplete-match/ng-include/span/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chile</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;one-column-hover ng-scope&quot;]/form[@class=&quot;ng-valid-maxlength ng-valid-step ng-invalid ng-invalid-required ng-valid-max-tags ng-valid-min-tags ng-valid-leftover-text ng-dirty ng-valid-parse&quot;]/div[@class=&quot;content-page wider-detail top-70px ng-scope&quot;]/div[2]/div[@class=&quot;row my-4 mx-30px&quot;]/div[@class=&quot;col-12 mt-4 align-items-start mx-0 pb-4&quot;]/div[@class=&quot;row w-100 align-items-start&quot;]/div[@class=&quot;col-6 pl-0&quot;]/div[@class=&quot;form-group mb-50px pb-3&quot;]/tags-input[@class=&quot;form-control p-0 has-success ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty ng-valid-max-tags ng-valid-min-tags ng-valid-leftover-text&quot;]/div[@class=&quot;host&quot;]/auto-complete[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;autocomplete ng-scope&quot;]/ul[@class=&quot;suggestion-list&quot;]/li[@class=&quot;suggestion-item ng-scope selected&quot;]/ti-autocomplete-match[@class=&quot;ng-isolate-scope&quot;]/ng-include[@class=&quot;ng-scope&quot;]/span[@class=&quot;ng-binding ng-scope&quot;]/em[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div[2]/form/div/div[2]/div[2]/div[16]/div/div/div/tags-input/div/auto-complete/div/ul/li[9]/ti-autocomplete-match/ng-include/span/em</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chiriquí (Panamá)'])[1]/following::em[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chinandega (Nicaragua)'])[1]/following::em[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carchi (Ecuador)'])[1]/preceding::em[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
   </webElementXpaths>
</WebElementEntity>
