<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CREACIONES</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6f2aa059-4030-4a1b-8b40-4080977eef34</testSuiteGuid>
   <testCaseLink>
      <guid>847a0d3c-7a98-43f9-ae5c-4f9fe55e8ab1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR COMPANY - ESTANDAR</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8c186019-3730-4111-84c2-26bf2cc461e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR COMPANY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cac3984-cea2-40d6-b118-31a0b5c99c62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b0aafad-31d1-438c-ab59-cfc1d67681e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee98e410-7849-4fe5-b2f2-af90966e502f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d43dbd33-ff95-453e-a1ae-4494de1db3d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0943c1d-1827-4ab7-8f35-e9fbc2043f88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>385b3a0d-4c91-40cd-accc-c0d45a1b9e25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0378b22c-0047-462e-9df8-302829555e82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR HITOS - ESTANDAR</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c6b683c5-a0a2-4641-a8bc-5faffe6d4841</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR HITOS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4fbe5f70-c862-4581-8fbc-c85ca64c32e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR NOTICIAS - ENTREVISTA - RECOMENDADO</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ea8e6522-e83e-4966-b356-f9ac51e64c17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR NOTICIAS - NATIVE - NO RECOMENDADO</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4d261877-7c9c-415a-a5d7-c49818358c6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR PERSONAS - ESTANDAR - ACCESO ESPECIAL</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>880332c1-3701-4ee7-8647-eb2c71acb720</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR PERSONAS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f3db6ba9-ade2-455e-a793-91f1dc9858a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR PROYECTOS - ESTANDAR</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a3843ade-ee84-4245-93ee-be8525abc368</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR PROYECTOS - PRA</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bf0c5d00-de05-44d6-ae27-12446a92e0fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR PROYECTOS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7281e8b2-639d-4b42-a9a5-d05c0501f0ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR REPORTES</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ecc60c3-4994-42c7-bc36-2766779794b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea6482c7-2fb4-4478-b272-b99be1c77ca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39628cb6-f572-4525-b582-7fe542eb5a48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b726100c-6b9d-4253-80f8-a9db85e6f94a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7065f61d-4a49-40a9-af8b-d1ec47826e98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f32ae24-e217-49b4-a20e-cae6e8934310</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>842732f3-9222-4e65-9ae7-338b30f563a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS - MODULO EDITAR/CREAR SET DE DATOS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18301065-bbfe-4841-9342-0b93fd9cde2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca3a65ec-67f1-4534-99c4-ba5244c8f527</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f041c06b-94d3-48e0-a586-64b65e1c6897</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba1dc3fb-1ce0-47b2-80f1-3e43602f1485</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32398b78-9336-46b4-a314-d00464744835</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f88cce8-6c5d-4dc6-a6e9-07f60f5a14c0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
